# Generated by Django 5.0.7 on 2024-08-04 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("repo_link", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("STARTED", "Started"),
                            ("BACKLOG", "Backlog"),
                        ],
                        default="OPEN",
                        max_length=100,
                    ),
                ),
                (
                    "author_role",
                    models.CharField(
                        choices=[
                            ("BACKEND", "Backend"),
                            ("FRONTEND", "Frontend"),
                            ("FULLSTCK", "Fullstck"),
                            ("QA", "QA"),
                            ("DESIGN", "Design"),
                            ("PM", "PM"),
                            ("DEVOPS", "Devops"),
                            ("OTHER", "Other"),
                        ],
                        default="BACKEND",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="User",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
