# Generated by Django 5.0.7 on 2024-08-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="author",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
